from typing import Any

from flo.render._publication import (
    PublicationBandContent,
    PublicationBounds,
    PublicationFigureRef,
    PublicationMargins,
    PublicationPageSpec,
    PublicationPlan,
    build_publication_canvas,
    materialize_publication_series,
)
from flo.render.options import RenderOptions
from flo.render.sppm.publication import build_sppm_publication_plan
from flo.render.sppm.publication_artifact import (
    render_sppm_typst_publication_artifact,
)
from flo.render.typst_publication import emit_typst_publication


def test_emit_typst_publication_preserves_page_and_band_context():
    canvas = build_publication_canvas(
        bounds=PublicationBounds(width_px=816, height_px=1056),
        margins=PublicationMargins(top_px=48, right_px=48, bottom_px=48, left_px=48),
        header_height_px=96,
        footer_height_px=72,
    )
    series = materialize_publication_series(
        series_id="main",
        title="Operations [Review]",
        kind="map",
        page_specs=(
            PublicationPageSpec(
                page_key="p1",
                canvas=canvas,
                header_content=PublicationBandContent(title="Operations [Review]"),
                footer_content=PublicationBandContent(notes=("Draft #1",)),
                figures=(
                    PublicationFigureRef(
                        figure_id="main-p1-figure",
                        asset_path="main-p1.svg",
                        alt_text="Operations map page 1",
                        source_node_ids=("start", "review"),
                    ),
                ),
            ),
            PublicationPageSpec(
                page_key="p2",
                canvas=canvas,
                footer_content=PublicationBandContent(
                    context_rows=(("Continues From", "main-p1"),)
                ),
            ),
        ),
    )
    plan = PublicationPlan(
        title="Operations [Review]",
        primary_series_id="main",
        series=(series,),
    )

    typst = emit_typst_publication(plan)

    assert typst.startswith("// Generated by FLO. Do not edit by hand.\n")
    assert "#set page(width: 816pt, height: 1056pt" in typst
    assert '#metadata((flo_page_id: "main-p1"))' in typst
    assert '#metadata((flo_page_id: "main-p2"))' in typst
    assert "#pagebreak()" in typst
    assert "= Operations \\[Review\\]" in typst
    assert "_Draft \\#1_" in typst
    assert "*Continues From:* main-p1" in typst
    assert (
        '#metadata((flo_figure_id: "main-p1-figure", asset_path: "main-p1.svg"))'
        in typst
    )
    assert "*Steps:* start, review" in typst


def test_build_sppm_publication_plan_paginates_with_stable_figure_references():
    process, nodes, edges = _publication_process()
    plan = build_sppm_publication_plan(
        process=process,
        options=RenderOptions.from_mapping(
            {
                "diagram": "sppm",
                "layout_overflow": "paginate",
                "layout_target_columns": 3,
                "publication_page_format": "letter",
            }
        ),
        nodes=nodes,
        edges=edges,
    )

    pages = plan.primary_series().pages
    assert [page.page_id for page in pages] == ["main-p1", "main-p2", "main-p3"]
    assert [page.figures[0].asset_path for page in pages] == [
        "main-p1.svg",
        "main-p2.svg",
        "main-p3.svg",
    ]
    assert pages[0].figures[0].source_node_ids == ("start", "prep", "a")
    assert pages[1].metadata["continuation_from"] == "main-p1"
    assert pages[1].metadata["continuation_to"] == "main-p3"
    assert pages[2].figures[0].source_node_ids == ("e", "end")
    typst = emit_typst_publication(plan)
    assert typst.count("#pagebreak()") == 2
    assert 'asset_path: "main-p2.svg"' in typst
    assert "*Steps:* start, prep, a" in typst
    assert "*Continues From:* main-p1" in typst


def test_render_sppm_typst_publication_artifact_exposes_plan_identity():
    process, nodes, edges = _publication_process()
    process = {**process, "nodes": nodes, "edges": edges}

    artifact = render_sppm_typst_publication_artifact(
        process,
        RenderOptions.from_mapping({"diagram": "sppm"}),
    )

    assert artifact.kind == "typst"
    assert artifact.backend == "typst"
    assert artifact.metadata["publication"]["primary_series_id"] == "main"
    assert artifact.metadata["publication"]["page_count"] == 1
    assert artifact.metadata["artifact_slots"] == ("child:prep",)
    assert "// Publication: Demo Process" in artifact.content


def _publication_process() -> tuple[
    dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]
]:
    process = {"process": {"id": "demo", "name": "Demo Process"}}
    nodes = [
        {"id": "start", "kind": "start", "name": "Start"},
        {"id": "prep", "kind": "subprocess", "name": "Prep"},
        {"id": "a", "kind": "task", "name": "A", "subprocess_parent": "prep"},
        {"id": "b", "kind": "task", "name": "B", "subprocess_parent": "prep"},
        {"id": "c", "kind": "task", "name": "C", "subprocess_parent": "prep"},
        {"id": "d", "kind": "task", "name": "D", "subprocess_parent": "prep"},
        {"id": "e", "kind": "task", "name": "E", "subprocess_parent": "prep"},
        {"id": "end", "kind": "end", "name": "End"},
    ]
    edges = [
        {"source": "start", "target": "prep"},
        {"source": "prep", "target": "a"},
        {"source": "a", "target": "b"},
        {"source": "b", "target": "c"},
        {"source": "c", "target": "d"},
        {"source": "d", "target": "e"},
        {"source": "e", "target": "end"},
    ]
    return process, nodes, edges
