"""Deterministic Typst emission from renderer-independent publication plans."""

from __future__ import annotations

from flo.render._publication import (
    PublicationBandContent,
    PublicationFigureRef,
    PublicationPage,
    PublicationPlan,
    PublicationRegion,
)


def emit_typst_publication(plan: PublicationPlan) -> str:
    """Emit deterministic Typst source for every page in a publication plan."""
    pages = tuple(page for series in plan.series for page in series.pages)
    if not pages:
        raise ValueError("Publication plan must contain at least one page.")

    lines = [
        "// Generated by FLO. Do not edit by hand.",
        f"// Publication: {_typst_text(plan.title)}",
    ]
    for page_index, page in enumerate(pages):
        if page_index:
            lines.append("#pagebreak()")
        lines.extend(_emit_page(page))
    return "\n".join(lines) + "\n"


def _emit_page(page: PublicationPage) -> list[str]:
    bounds = page.canvas.bounds
    margins = page.canvas.margins
    width = _require_dimension(bounds.width_px, "width")
    height = _require_dimension(bounds.height_px, "height")
    lines = [
        (
            f"#set page(width: {width}pt, height: {height}pt, "
            f"margin: (top: {margins.top_px}pt, right: {margins.right_px}pt, "
            f"bottom: {margins.bottom_px}pt, left: {margins.left_px}pt))"
        ),
        f"// FLO page: {_typst_text(page.page_id)}",
        f'#metadata((flo_page_id: "{_typst_string(page.page_id)}"))',
    ]
    for band_name in ("header", "footer"):
        band = page.band(band_name)
        if band is not None:
            lines.extend(_emit_band(band.region, band.content, band_name))
    for figure in page.figures:
        lines.extend(_emit_figure_reference(figure))
    return lines


def _emit_band(
    region: PublicationRegion,
    content: PublicationBandContent,
    name: str,
) -> list[str]:
    lines = [f"// FLO {name} band: {_typst_text(region.name)}"]
    if content.title:
        lines.append(f"= {_typst_text(content.title)}")
    lines.extend(_emit_rows(content.rows))
    lines.extend(_emit_rows(content.context_rows))
    lines.extend(f"_{_typst_text(note)}_" for note in content.notes)
    return lines


def _emit_rows(rows: tuple[tuple[str, str], ...]) -> list[str]:
    return [f"*{_typst_text(label)}:* {_typst_text(value)}" for label, value in rows]


def _emit_figure_reference(figure: PublicationFigureRef) -> list[str]:
    figure_id = _typst_string(figure.figure_id)
    asset_path = _typst_string(figure.asset_path)
    alt_text = _typst_string(figure.alt_text)
    source_node_ids = figure.source_node_ids
    lines = [
        f'#metadata((flo_figure_id: "{figure_id}", asset_path: "{asset_path}"))',
        f"// FLO figure asset: {_typst_text(asset_path)}",
        f'#image("{asset_path}", width: 100%, alt: "{alt_text}")',
    ]
    if source_node_ids:
        references = ", ".join(_typst_text(str(node_id)) for node_id in source_node_ids)
        lines.append(f"*Steps:* {references}")
    return lines


def _require_dimension(value: int | None, name: str) -> int:
    if value is None or value <= 0:
        raise ValueError(f"Publication page {name} must be a positive integer.")
    return value


def _typst_text(value: str) -> str:
    return value.replace("#", "\\#").replace("[", "\\[").replace("]", "\\]")


def _typst_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
